package cm.sigeris.roomdatabase.fragments.add


import android.os.Bundle
import android.text.TextUtils
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Toast
import androidx.lifecycle.ViewModelProvider
import androidx.navigation.fragment.findNavController
import cm.sigeris.roomdatabase.R
import cm.sigeris.roomdatabase.model.User
import cm.sigeris.roomdatabase.viewmodel.UserViewModel
import kotlinx.android.synthetic.main.fragment_add.*
import kotlinx.android.synthetic.main.fragment_add.view.*

class AddFragment : Fragment() {
    private lateinit var mUserViewModel: UserViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
        val view = inflater.inflate(R.layout.fragment_add, container, false)
        mUserViewModel = ViewModelProvider(this).get(UserViewModel::class.java)
        view.btnInsert.setOnClickListener {
            insertDataToDataBase()
//            val userList = ArrayList<User>()
//
//            userList.add(User(0, "WOUAGUIE TCHASSEM BARACK  AUGUSTIN", "", (12..24).random()))
//        userList.add(User(0, "KENGNE TEDOM SERAPHIN", "", (12..24).random()))
//        userList.add(User(0, "DJEMBISSI  WAFO  BRIANA", "", (12..24).random()))
//        userList.add(User(0, "MOTUE  KENGNE  LAURINA  CLARENCE", "", (12..24).random()))
//        userList.add(User(0, "KUATE  FOTSO  KEVIN  STEVE", "", (12..24).random()))
//        userList.add(User(0, "MOCHE JOANA FLORE", "", (12..24).random()))
//        userList.add(User(0, "KAMGA SIMO VINCENT DE PAUL", "", (12..24).random()))
//        userList.add(User(0, "METCHUM KUATE PRINCESSE LYDIE", "", (12..24).random()))
//        userList.add(User(0, "NOWA WABO JEAN BAPTISTE", "", (12..24).random()))
//        userList.add(User(0, "GUESSOM TUMCHOU STEVE GERARD", "", (12..24).random()))
//        userList.add(User(0, "MEGNO TATCHUM JESSICA MERVEILLE", "", (12..24).random()))
//        userList.add(User(0, "BOYOM ALEX THEOPHILE", "", (12..24).random()))
//        userList.add(User(0, "NOUADZE CHIZE JURICE LE PRINCE", "", (12..24).random()))
//        userList.add(User(0, "GUETCHUESSI TUEMGNE SORELLE", "", (12..24).random()))
//        userList.add(User(0, "KUETCHE BRAYANE ATHANASE", "", (12..24).random()))
//        userList.add(User(0, "NOUEBISSI MERVEILLE SOLANGE", "", (12..24).random()))
//        userList.add(User(0, "METSEGOUM FONGANG MERVEILLE", "", (12..24).random()))
//        userList.add(User(0, "TALOM  SOH  BELL  JACKSON", "", (12..24).random()))
//        userList.add(User(0, "TAMNO TAGNE DYLANE FRANTZ", "", (12..24).random()))
//        userList.add(User(0, "KENGNE TABOULASSOM FRANCIS CABREL", "", (12..24).random()))
//        userList.add(User(0, "KENGNE KAMGA FRANCOISE", "", (12..24).random()))
//        userList.add(User(0, "WAFFO KAPING LOI JOSPAN", "", (12..24).random()))
//        userList.add(User(0, "KENGNE KUATE ISMAEL ", "", (12..24).random()))
//        userList.add(User(0, "FOKO  TOGUE ARSENE FERDINAND", "", (12..24).random()))
//        userList.add(User(0, "TOKAM MICHEL FABRICE", "", (12..24).random()))
//        userList.add(User(0, "NWOUOTCHUENG ROSLIN D     IDERO", "", (12..24).random()))
//        userList.add(User(0, "KAMGNO KAPTUE HERMANN", "", (12..24).random()))
//        userList.add(User(0, "ZEKOU PATRICK MICHAEL", "", (12..24).random()))
//        userList.add(User(0, "SIMO  KAPCHE  WILFRIED", "", (12..24).random()))
//        userList.add(User(0, "LAYOU FEZEU BEN ARTHUR", "", (12..24).random()))
//        userList.add(User(0, "KAMDEM  GILDAS  ARMEL", "", (12..24).random()))
//        userList.add(User(0, "DJUIKOM SYLVIE   FLORE", "", (12..24).random()))
//        userList.add(User(0, "FOTSO NGNOGUEM THEOPHANE SYLVAIN", "", (12..24).random()))
//        userList.add(User(0, "METIEGE FOWA VANESSA GLADYS", "", (12..24).random()))
//        userList.add(User(0, "NOUEGUE TUEKAM DAREL ENZO", "", (12..24).random()))
//        userList.add(User(0, "NOTOUOM TOGUEM MARC BRAEL", "", (12..24).random()))
//        userList.add(User(0, "DJATIO SEGNING ARNOL PRINCE", "", (12..24).random()))
//        userList.add(User(0, "TATCHUM CHATUE JOSEPH UGOR", "", (12..24).random()))
//        userList.add(User(0, "FOTSO  KOUNGA   PRINCE  MICHEL", "", (12..24).random()))
//        userList.add(User(0, "LIENCHE  SIBAFO  CLARITA  JOYCE", "", (12..24).random()))
//        userList.add(User(0, "NOUBISSI KAMDEM CYRILLE OKRY", "", (12..24).random()))
//        userList.add(User(0, "DJOMKOUO KONGA IDRISSE", "", (12..24).random()))
//        userList.add(User(0, "YOUMBI NTCHENGA DILANE ANDERSON", "", (12..24).random()))
//        userList.add(User(0, "TUENE  FOADJO  BENEDICTE SUZANNE VANESSA", "", (12..24).random()))
//        userList.add(User(0, "NKOUNGA  KENGUE   NATHANAEL", "", (12..24).random()))
//        userList.add(User(0, "TAGNE TECHE JEAN PATRICK", "", (12..24).random()))
//        userList.add(User(0, "TUENO KOUOKAM RUBAIN CAMILLE", "", (12..24).random()))
//        userList.add(User(0, "NGUEUTUE KAMGA JOSIANE", "", (12..24).random()))
//        userList.add(User(0, "DJUIDJIE SOUP GISELE", "", (12..24).random()))
//        userList.add(User(0, "MAGNE NADINE NAIVA", "", (12..24).random()))
//        userList.add(User(0, "ELAH MARIE BRAYANNE", "", (12..24).random()))
//        userList.add(User(0, "DJUIKOM FOTSO CHRISTELLE   LAURE", "", (12..24).random()))
//        userList.add(User(0, "WATO DASSI JOSEPH", "", (12..24).random()))
//        userList.add(User(0, "KAMGA FOTSO RONALD", "", (12..24).random()))
//        userList.add(User(0, "FOGUE BOPDA SAMUEL DIMITRI", "", (12..24).random()))
//        userList.add(User(0, "FOTSO NESTOR LEGRAND", "", (12..24).random()))
//        userList.add(User(0, "MOKO  FOASSE  FRANCINE  LAURE", "", (12..24).random()))
//        userList.add(User(0, "WAFO KUATE PIERRE ULRICH", "", (12..24).random()))
//        userList.add(User(0, "TSAMO  HORCHELLE  MEGANNE", "", (12..24).random()))
//        userList.add(User(0, "TAKAM TAMU LANDRY STVE", "", (12..24).random()))
//        userList.add(User(0, "METAGNE TASSAM JASMINE LA DOUCE", "", (12..24).random()))
//        userList.add(User(0, "BOPDA OSE WILLIAMS", "", (12..24).random()))
//        userList.add(User(0, "NZOUKOU KUATE LAURICE BLONDELE", "", (12..24).random()))
//        userList.add(User(0, "KAKENGNE TOUKAM MATHIEU BAUREL", "", (12..24).random()))
//        userList.add(User(0, "JOUEGO TAGNE CHARLETTE RACHELLE", "", (12..24).random()))
//        userList.add(User(0, "MAFO TABUE SIDORENCE ARIELLE", "", (12..24).random()))
//        userList.add(User(0, "NOGUE TALLA LAEU", "", (12..24).random()))
//        userList.add(User(0, "WOUAGUIE TCHASSEM BARACK AUGUSTIN", "", (12..24).random()))
//        userList.add(User(0, "GUIFFO KAMDEM GISLAIN", "", (12..24).random()))
//        userList.add(User(0, "MAMGNO TALLA STTABLONE", "", (12..24).random()))
//        userList.add(User(0, "TAGNE TAPPA YOVANE MIGUIEL", "", (12..24).random()))
//        userList.add(User(0, "KAMDEM FOTSO JORES IVAN", "", (12..24).random()))
//        userList.add(User(0, "NDJINDOULA VENEL BENAYA", "", (12..24).random()))
//        userList.add(User(0, "FOSSUO  TEBUE  CHRIST  RAYAND", "", (12..24).random()))
//        userList.add(User(0, "CHEKUMO FOGUE RYAN JIRES", "", (12..24).random()))
//        userList.add(User(0, "MINFELE EVINA MATHILDE", "", (12..24).random()))
//        userList.add(User(0, "DJOMMO WABO NARCISSE JIRRES", "", (12..24).random()))
//        userList.add(User(0, "MEWABO KAMGA DANIELA ABRIGAELLE", "", (12..24).random()))
//        userList.add(User(0, "FOGNO BOUOPDA ASAPH", "", (12..24).random()))
//        userList.add(User(0, "ADJAP SOPHIE", "", (12..24).random()))
//        userList.add(User(0, "FOSSOUO FOKO JOSPIN JUNIOR", "", (12..24).random()))
//        userList.add(User(0, "TOCHE FOTSO FRANCK VALERE", "", (12..24).random()))
//        userList.add(User(0, "MOKAM TCHOUTEDJEM MARTHE CARELLE", "", (12..24).random()))
//        userList.add(User(0, "TAGNE FRANCK STEVE", "", (12..24).random()))
//        userList.add(User(0, "GUEMGNE AUBINE DARELLE", "", (12..24).random()))
//        userList.add(User(0, "DJOMENI MINETTE LAURE", "", (12..24).random()))
//        userList.add(User(0, "TUEDJO FABIOLA CHARLENE", "", (12..24).random()))
//        userList.add(User(0, "SIMO KUATE EMMANUEL JUNIOR", "", (12..24).random()))
//        userList.add(User(0, "YOUBI TOUMSSI ARTHUR KEVIN", "", (12..24).random()))
//        userList.add(User(0, "POUAKA FONO DONATIEN", "", (12..24).random()))
//        userList.add(User(0, "KUATE SIRIL APPOLINAIRE", "", (12..24).random()))
//        userList.add(User(0, "KAMGNO SIKENGNE ISMAEL NOEL", "", (12..24).random()))
//        userList.add(User(0, "KAMGA TAYOU DAVID JONATHAN", "", (12..24).random()))
//        userList.add(User(0, "KAPCHE LEONTINE", "", (12..24).random()))
//        userList.add(User(0, "KOUOMOU TEGUIA CHRIST ILARIO", "", (12..24).random()))
//        userList.add(User(0, "TATI ARLANE CABREL", "", (12..24).random()))
//        userList.add(User(0, "BOPDA  TAGNE  MIGUELLE", "", (12..24).random()))
//        userList.add(User(0, "KAMGA   KAMGA  EMPATHIE  MIKA", "", (12..24).random()))
//        userList.add(User(0, "TAGNE KENGNE CABREL", "", (12..24).random()))
//        userList.add(User(0, "DJUIDJE GNIE VIDOLLY LORINCE", "", (12..24).random()))
//        userList.add(User(0, "GOMTO TCHAKOUTE ROIS DAVID MOLIERE", "", (12..24).random()))
//        userList.add(User(0, "FOTO DJEMO ARNAUD CHRISTIAN", "", (12..24).random()))
//        userList.add(User(0, "KUATE ALAIN SOREL", "", (12..24).random()))
//        userList.add(User(0, "KENGNE KAMGNO ARCHANGE RAYAN", "", (12..24).random()))
//        userList.add(User(0, "MAMTO GNOTSO YASMINE", "", (12..24).random()))
//        userList.add(User(0, "TOKAM TOUMPING LORENZO CABREL", "", (12..24).random()))
//        userList.add(User(0, "DEFFO JORDANE KEVIN", "", (12..24).random()))
//        userList.add(User(0, "KENGNE WAFO JUDICAEL", "", (12..24).random()))
//        userList.add(User(0, "SITAMDZE FOTUE BORIS ARMAND", "", (12..24).random()))
//        userList.add(User(0, "SACSSUM KAMGA VINCENT DE PAUL", "", (12..24).random()))
//        userList.add(User(0, "SEUMOU TCHAKOUNTE ROSTAND", "", (12..24).random()))
//        userList.add(User(0, "KENGNE PRINCE ANGE", "", (12..24).random()))
//        userList.add(User(0, "TATOCHE FODOUOP GABAIN", "", (12..24).random()))
//        userList.add(User(0, "MOTOUM FOTSO SANDRA KELIA", "", (12..24).random()))
//        userList.add(User(0, "KAMGA MOUDZE JEAN MICHEL", "", (12..24).random()))
//        userList.add(User(0, "MANDE TAYOUO RAISSA DIENY", "", (12..24).random()))
//        userList.add(User(0, "TAMNO  TOKAM  BRAYAN  BRICE", "", (12..24).random()))
//        userList.add(User(0, "FOKAM DEFO BORICE CABREL", "", (12..24).random()))
//        userList.add(User(0, "FOKAM TAMSSU PRISCA", "", (12..24).random()))
//        userList.add(User(0, "MACHIE NKOUASSI MARTHE NOELLY", "", (12..24).random()))
//        userList.add(User(0, "TAGNE FOTSO CHRISTIAN", "", (12..24).random()))
//        userList.add(User(0, "FOTSO TATCHUM PURICH DUCRES", "", (12..24).random()))
//        userList.add(User(0, "PUEPI FOTSO JUSTIN DIDEROT", "", (12..24).random()))
//        userList.add(User(0, "DZUDIE TALOM JUSTIN", "", (12..24).random()))
//        userList.add(User(0, "OBAMA BERNADETTE CHANCELINE", "", (12..24).random()))
//        userList.add(User(0, "BEMMO TOGUEM CLAUDIA", "", (12..24).random()))
//        userList.add(User(0, "TENE TAPA MAUREL ROSAIR", "", (12..24).random()))
//        userList.add(User(0, "KENGNE CHATUE TATIANA VICTOIRE", "", (12..24).random()))
//        userList.add(User(0, "KUATE KENGNE CLOVIS CABREL", "", (12..24).random()))
//        userList.add(User(0, "KOUAMO   WAFO FRANKY", "", (12..24).random()))
//        userList.add(User(0, "KUATE VALDEZE AURELIEN", "", (12..24).random()))
//        userList.add(User(0, "TIAKOU  WAMI  FAELLE  KEROS", "", (12..24).random()))
//        userList.add(User(0, "TALLA STEPHANE HERVE", "", (12..24).random()))
//        userList.add(User(0, "DJIMOFO FOKA STYVE", "", (12..24).random()))
//        userList.add(User(0, "CHOUHE LUNA STELLA", "", (12..24).random()))
//        userList.add(User(0, "KENGNE KOTUE HERVE", "", (12..24).random()))
//        userList.add(User(0, "MEDJOM NOTUE MIREILLE", "", (12..24).random()))
//        userList.add(User(0, "DJUIDJA CARINE MESMINE", "", (12..24).random()))
//        userList.add(User(0, "MAGNE SIMO HELENE ADRIENNE", "", (12..24).random()))
//        userList.add(User(0, "TEINGO DOROTHEE BLANCHE SYLVIANE", "", (12..24).random()))
//        userList.add(User(0, "YESSIBI VALDAIS", "", (12..24).random()))
//        userList.add(User(0, "CHOUGOUOG FEZE KEYS FORTUNE", "", (12..24).random()))
//        userList.add(User(0, "VOEULEU ROUCEL CABREL", "", (12..24).random()))
//        userList.add(User(0, "TSANGA NANA JEANNE MARIE LACHOINA ", "", (12..24).random()))
//        userList.add(User(0, "FOTSO DJUIKOM MYRICE GERMINE", "", (12..24).random()))
//        userList.add(User(0, "ZAM NICOLAS", "", (12..24).random()))
//        userList.add(User(0, "FODOUOP   RAILLE  JORDAN   ROOSVELL", "", (12..24).random()))
//        userList.add(User(0, "SADO PIERRE CEDRIC", "", (12..24).random()))
//        userList.add(User(0, "KAMGA TAMNO JOSEPH", "", (12..24).random()))
//        userList.add(User(0, "KUATE KUITEING GASTON", "", (12..24).random()))
//        userList.add(User(0, "TEBOU TABUE ROMARIC JUNIOR", "", (12..24).random()))
//        userList.add(User(0, "NDOFANG KUE ANGE FORTUNE", "", (12..24).random()))
//        userList.add(User(0, "WABO NKOUNGA MICHEL YRESSE", "", (12..24).random()))
//        userList.add(User(0, "NOSSA KENFACK MAEVA GUERS", "", (12..24).random()))
//        userList.add(User(0, "MOUNOUE NICOLE", "", (12..24).random()))
//        userList.add(User(0, "TATCHUM NELSON CLAUDE", "", (12..24).random()))
//        userList.add(User(0, "MOTUE TEDOM NADINE ANGE", "", (12..24).random()))
//        userList.add(User(0, "SIMO FOTSO FRANKY ARMAND", "", (12..24).random()))
//        userList.add(User(0, "WAFO TEKAM DILANE CLIF", "", (12..24).random()))
//        userList.add(User(0, "YOUMSI JEAN EMMANUEL", "", (12..24).random()))
//        userList.add(User(0, "KENGNE ELVIS JOEL ", "", (12..24).random()))
//        userList.add(User(0, "DJOUGANG SANBANG INESS PAULINE", "", (12..24).random()))
//        userList.add(User(0, "KENGNE   LELE  JUDICAEL  ROSVEL", "", (12..24).random()))
//        userList.add(User(0, "DJOUGANG SANBANG INESS PAULINE", "", (12..24).random()))
//        userList.add(User(0, "WAFO KAMGA MARCO LOYIS", "", (12..24).random()))
//        userList.add(User(0, "TAMOKWE FOTSO JOSIAS", "", (12..24).random()))
//        userList.add(User(0, "GUEYO WAFO PRINCE MIGUEL", "", (12..24).random()))
//        userList.add(User(0, "KUGNE GUIFO ARIEL GYLDAS", "", (12..24).random()))
//        userList.add(User(0, "TOHBOU TAMTO MAURICE", "", (12..24).random()))
//        userList.add(User(0, "DJOKO FONGANG LEONEL RICHY", "", (12..24).random()))
//        userList.add(User(0, "FOTSO ANGE GILBERT", "", (12..24).random()))
//        userList.add(User(0, "KAMDEM LUC JEREMIE", "", (12..24).random()))
//        userList.add(User(0, "FOKAM DIEUDONNE", "", (12..24).random()))
//        userList.add(User(0, "KENGMO CRHIST", "", (12..24).random()))
//        userList.add(User(0, "MATAGNE OUAMBO IRENE LOVE", "", (12..24).random()))
//        userList.add(User(0, "CHOUDJA OUABO ELIE DONAL", "", (12..24).random()))
//        userList.add(User(0, "TABEKO WABO CHRISLIN HERMANN", "", (12..24).random()))
//        userList.add(User(0, "CHAGOM BARNABAS", "", (12..24).random()))
//        userList.add(User(0, "KENGNE PRINCE   IGOR", "", (12..24).random()))
//        userList.add(User(0, "FOTSO VICTOR", "", (12..24).random()))
//        userList.add(User(0, "FOKAM WAFO RID PRINCE", "", (12..24).random()))
//        userList.add(User(0, "FANLE OUATO AUDE VANELLE", "", (12..24).random()))
//        userList.add(User(0, "NGABA FONKEU DIMITRI", "", (12..24).random()))
//        userList.add(User(0, "FUTHE FRANCHESSE MALIANO", "", (12..24).random()))
//        userList.add(User(0, "FOKAM KUATE EMMANUEL JORDAN", "", (12..24).random()))
//        userList.add(User(0, "FODOUOP TAGNE IGORE RIVALDO", "", (12..24).random()))
//        userList.add(User(0, "MATIEDJEU CAROLE BEBILINE", "", (12..24).random()))
//        userList.add(User(0, "MOGUE KUATE PRINCESS", "", (12..24).random()))
//        userList.add(User(0, "DJUIGNE  STELLA  BERLINE", "", (12..24).random()))
//        userList.add(User(0, "DJUIKOM LELE INES DORIANE", "", (12..24).random()))
//        userList.add(User(0, "TETIO  DEFFO  ARSEL  KELEAN", "", (12..24).random()))
//        userList.add(User(0, "MOGOUN NADINE SIDONIE", "", (12..24).random()))
//        userList.add(User(0, "CHOUPO MOUDZE ROMAIN", "", (12..24).random()))
//        userList.add(User(0, "FUMTCHUM FOLENG BLECK CARIN", "", (12..24).random()))
//        userList.add(User(0, "TAGNE  TALOM  CHRISTIAN  LENS", "", (12..24).random()))
//        userList.add(User(0, "SENGUE JOEL STEVE", "", (12..24).random()))
//        userList.add(User(0, "TAGUELA  TCHINDA  GOOD LIVE", "", (12..24).random()))
//        userList.add(User(0, "TAGAKO ROBERT", "", (12..24).random()))
//        userList.add(User(0, "MEBOU FODOUOP GRACE FABIOLA", "", (12..24).random()))
//        userList.add(User(0, "DJUIKOM WAFFO CABRELLE MERVEILLE", "", (12..24).random()))
//        userList.add(User(0, "MKOUNGA NGOMPE MARC RONNEL", "", (12..24).random()))
//        userList.add(User(0, "TALLA   YOUMBI  HONORE", "", (12..24).random()))
//        userList.add(User(0, "NDOMGUE WABO BRUNO JIRES", "", (12..24).random()))
//        userList.add(User(0, "TAKOUMBE FOTSO FRANKLIN CEDRIC", "", (12..24).random()))
//        userList.add(User(0, "TAGNE FOTSO CLOVIS", "", (12..24).random()))
//        userList.add(User(0, "FOTSO DJOUTIO LAURENT PASCAL", "", (12..24).random()))
//        userList.add(User(0, "YOUMSSI NKOUNGA ARMAND", "", (12..24).random()))
//        userList.add(User(0, "TABOUE WAFO ELVIS", "", (12..24).random()))
//        userList.add(User(0, "KAMGA TAMTO YVES ROLAND", "", (12..24).random()))
//        userList.add(User(0, "FOTSI HUGUES AIME", "", (12..24).random()))
//        userList.add(User(0, "FOTSO  KUATE  BRICE THIERRY", "", (12..24).random()))
//        userList.add(User(0, "SIMO NDEFFO NARCISSE JORDAN", "", (12..24).random()))
//        userList.add(User(0, "TOGOUO JEAN MARIE", "", (12..24).random()))
//        userList.add(User(0, "TAMNO SIAKA ALEX", "", (12..24).random()))
//        userList.add(User(0, "REINE MOCHE YVONE CLAIRE", "", (12..24).random()))
//        userList.add(User(0, "FOSSOUO NOKAM YVES YANNICK", "", (12..24).random()))
//        userList.add(User(0, "KEPGANG TCHINANG JULIENNE DIVINE", "", (12..24).random()))
//        userList.add(User(0, "TOUKAM WABO CHRISTIAN", "", (12..24).random()))
//        userList.add(User(0, "KAPTUE MOTUE LAURIANNE GAELLE", "", (12..24).random()))
//        userList.add(User(0, "GNOTOUOM TAMKO DIVINE RONALDO", "", (12..24).random()))
//        userList.add(User(0, "FOWA  KAEGOUM  JUDICAEL", "", (12..24).random()))
//        userList.add(User(0, "KAMGA JOSPIN JOEL", "", (12..24).random()))
//        userList.add(User(0, "KAMGA KEVIN FREDY", "", (12..24).random()))
//        userList.add(User(0, "YMELE  MEKENGNANG  SONTIA   LEZA", "", (12..24).random()))
//        userList.add(User(0, "FOKAM  KOUOKAM  INNOCENT", "", (12..24).random()))
//        userList.add(User(0, "TALOM  TABUE ACHIL", "", (12..24).random()))
//        userList.add(User(0, "KENGNE KUATE ISMAËL JORDAN", "", (12..24).random()))
//        userList.add(User(0, "KAMDEM TAGNE   CHRIST BRANDON", "", (12..24).random()))
//        userList.add(User(0, "TENO PRINCE AROLE", "", (12..24).random()))
//        userList.add(User(0, "KUATE KAMGA IVAN FRITZ", "", (12..24).random()))
//        userList.add(User(0, "KAMNE OLIVIER JUNIOR", "", (12..24).random()))
//        userList.add(User(0, "MOKAM KUETCHE KEVINE LAURE", "", (12..24).random()))
//        userList.add(User(0, "FOKO FOTSI DAVID ULRICH", "", (12..24).random()))
//        userList.add(User(0, "SIMO KAMGA LARYSSE CHANCELLE", "", (12..24).random()))
//        userList.add(User(0, "TOKAM TAMGUE BERTRAN", "", (12..24).random()))
//        userList.add(User(0, "POUMBISSI MAMAÏ MURIELLE", "", (12..24).random()))
//        userList.add(User(0, "DJECHE TOUKAM JOY BRAYANE", "", (12..24).random()))
//        userList.add(User(0, "FONO GABRIEL ROSTAND", "", (12..24).random()))
//        userList.add(User(0, "FOTSO  TABUGUIA  FRANCK  BRAYAN", "", (12..24).random()))
//        userList.add(User(0, "GUIFFO KAMGNE MAGLOIRE FOE", "", (12..24).random()))
//        userList.add(User(0, "KAPCHE KENGNE MAÏVA", "", (12..24).random()))
//        userList.add(User(0, "WAFFO  TEKAM  IDRISS  ARMEL", "", (12..24).random()))
//        userList.add(User(0, "TAKAM NKOUASSI LEONNEL NATHAN", "", (12..24).random()))
//        userList.add(User(0, "FOUNAYIA FOUNAYIA MICHEL CABREL", "", (12..24).random()))
//        userList.add(User(0, "TAGNE KAMGA LOÏC ARNOLD", "", (12..24).random()))
//        userList.add(User(0, "FOKOU  ANGE CHIDERICK", "", (12..24).random()))
//        userList.add(User(0, "SIMO MARIE SHITYA LAGRACE", "", (12..24).random()))
//        userList.add(User(0, "KAMKUINO POUOKAM FRANCK MICAEL", "", (12..24).random()))
//        userList.add(User(0, "TATCHUM JOSEPH LUTRESS", "", (12..24).random()))
//        userList.add(User(0, "NGNOCHIE FRANCK BOREL", "", (12..24).random()))
//            for (i in userList){
//                mUserViewModel.addUser(i.copy())
//            }
        }

        return view
    }

    private fun insertDataToDataBase() {
        val firtName = edtFname.text.toString()
        val lastName = edtLname.text.toString()
        val age = edtAge.text.toString()
        if(formValidation(firtName, lastName, age)){
            val user = User(0, firtName.lowercase(), lastName.lowercase(), age.toInt())
            mUserViewModel.addUser(user)
            Toast.makeText(requireContext(), "successfully inserted", Toast.LENGTH_SHORT).show()
            findNavController().navigate(R.id.action_addFragment_to_listFragment)
        }else{
            Toast.makeText(requireContext(), "Please fill all fields", Toast.LENGTH_SHORT).show()
        }
    }

    private fun formValidation(firtName: String, lastname: String, age: String): Boolean {
        //return !(TextUtils.isEmpty(firtName) && TextUtils.isEmpty(lastname) && TextUtils.isEmpty(age))
        if(firtName.isEmpty()){
            edtFname.error = "enter a valid first name"
            edtFname.requestFocus()
            return false
        }
        if(lastname.isEmpty()){
            edtLname.error = "enter a valid last name"
            edtLname.requestFocus()
            return false
        }
        if(age.toString().length == 0){
            edtAge.error = "enter a valid age"
            edtAge.requestFocus()
            return false
        }
        return true
    }
}